version: '3'
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-network
  website:
    image: ghcr.io/pr0xximity999/blog:live
    ports:
      - "3001:3001"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true